export const GET_APPOINTMENTS = "GET_APPOINTMENTS";
export const ADD_APPOINTMENT = "ADD_APPOINTMENT";
export const UPDATE_APPOINTMENT = "UPDATE_APPOINTMENT";
export const DELETE_APPOINTMENT = "DELETE_APPOINTMENT";
export const APPOINTMENT_LOADING = "APPOINTMENT_LOADING";
export const GET_ALLLIST = "GET_ALLLIST";

export const GET_ITEMS = "GET_ITEMS";
export const ADD_ITEM = "ADD_ITEM";
export const DELETE_ITEM = "DELETE_ITEM";
export const ITEMS_LOADING = "ITEMS_LOADING";
export const USER_LOADED = "USER_LOADED";
export const USER_LOADING = "USER_LOADING";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const GET_USERS = "GET_USERS";
export const ADD_USERS = "ADD_USERS";
export const DELETE_USERS = "DELETE_USERS";
export const USERS_LOADING = "USERS_LOADING";

export const GET_ROOMS = "GET_ROOMS";
export const ADD_ROOMS = "ADD_ROOMS";
export const DELETE_ROOMS = "DELETE_ROOMS";
export const ROOMS_LOADING = "ROOMS_LOADING";
